### ISSUE TITLE
aws bosh plugin fails to deploy for private ip addresses

### ISSUE THREAD

**Issue by haydonryan** [enaml-ops/omg-cli#35] opened 2016-11-09 21:43 UTC
```
omg aws \
--mode uaa \
--aws-subnet subnet-X \
--aws-pem-pathX \
--aws-access-key  X \
--aws-secret X \
--aws-instance-size t2.micro \
--aws-region us-west-1 \
--aws-availability-zone us-west-1b \
--cidr 10.0.16.0/20 \
--gateway 10.0.16.1 \
--dns 10.0.16.2 \
--bosh-private-ip 10.0.16.6 \
--aws-security-group enamltest
```

gives this error:
```
Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Creating VM:
        Creating vm with stemcell cid 'ami-74b7f414 light':
          CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"No IP provided for vip network `public'","ok_to_retry":false}
```

**Comment by zmb3** [comment] 2016-11-15 14:40
Closing as duplicate of #31

**Closed as completed by zmb3** 2016-11-15 14:40 UTC
